# Generated by Django 3.1 on 2020-08-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200809_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='isCustomr',
            new_name='is_customer',
        ),
    ]
