# Generated by Django 3.1 on 2020-08-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
