# Generated by Django 3.1 on 2020-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200810_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='CREATED', max_length=20),
            preserve_default=False,
        ),
    ]
